### ISSUE TITLE
What means var global log in postgresql_user.py ?

### ISSUE THREAD

**Issue by sach3000** [tnt4brain/ansible-pg8k#1]
Hi,
After executing ansible task:
```postgresql_user: name: "{{ PG_USER }}"
    password: "{{ PG_PASSWORD }}"
    role_attr_flags: nosuperuser
    state: present
    fail_on_user: yes
    login_unix_socket: "/var/run/postgresql/.s.PGSQL.5432"
  become: yes 
  become_user: postgres
```
i get error message:
`ansible_postgresql_user_payload.zip/ansible/modules/postgresql_user.py\", line 456, in user_alter\r\nUnboundLocalError: local variable 'log'`

This is called function `user_alter` which contain `global log`

**Comment by tnt4brain** [comment]
It was just forgotten debug logging statement. Fixed.
